swagger: "2.0"

info:
  title: "My first API"
  version: "1.0"

basePath: /v1.0

paths:
  /items/:
    get:
      responses:
        '200':
          description: 'Fetch a list of items'
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'

  # /arrays/:
  #   get:
  #     responses:
  #       '200':
  #         description: 'Fetch list of names'
  #         schema:
  #           type: array
  #           items:
  #             $ref: '#/definitions/Array'
            

definitions:
  Item:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: { type: string }
      
  # Array:
  #   type: object
  #   properties:
  #     first_name: { type: string }
  #     last_name: { type: string }
      
    

